name: moneymap
description: "MoneyMap is a simple and privacy-focused personal finance tracker app.
  Track your daily expenses, view spending history, and manage your money — all offline,
  with no signup required"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  lottie: ^3.3.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/plusloader.json
    - lib/assets/moneymap_logo.png
